### ISSUE TITLE
Link to ports in other languages

### ISSUE THREAD

**Issue by sschuberth** [dmgerman/ninka#19]
I think it would be nice if the README (after being converted to markdown format) would link to known ports of Ninka to other programming languages. The only port I'm aware of right now is [JNinka](https://github.com/whitesource/jninka).

**Comment by dmgerman** [comment]
what is wrong with using org mode? It is way more powerful than markdown.

-dmg

On Fri, Sep 4, 2015 at 8:14 AM, Sebastian Schuberth <
notifications@github.com> wrote:

> I think it would be nice if the README (after being converted to markdown
> format) would link to known ports of Ninka to other programming languages.
> The only port I'm aware of right now is JNinka
> <https://github.com/whitesource/jninka>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmgerman/ninka/issues/19>.
>



-- 
--dmg

---
Daniel M. German
http://turingmachine.org

**Comment by sschuberth** [comment]
I don't know org mode. I was mentioning markdown as that's what GitHub uses by default to convert the `README(.md)` to HTML with clickable links. However, [it looks like GitHub would also be able to render org files](http://webapps.stackexchange.com/questions/45979/how-to-change-appearance-of-org-mode-files-on-github). You probably just need to rename the `README` to `README.org`.

**Comment by dmgerman** [comment]
rename README to README.org. References to other forks will not be added (at least for the time being).

**Comment by sschuberth** [comment]
For the record, please note that I was not talking about *forks*, but *ports*. Forks, as long as they are hosted on GitHub, are linked automatically. But ports naturally are not, as they are rewrites in other languages / for other platforms that to do share any code with the original projects.
